# Generated by Django 5.0 on 2023-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0003_alter_abbreviation_inscription_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='people',
            field=models.ManyToManyField(blank=True, to='lepcismagna.person'),
        ),
    ]
