# Generated by Django 5.0 on 2023-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0005_alter_inscription_entry_creator_userdossier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('inscriptions', models.ManyToManyField(blank=True, to='lepcismagna.inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='languages',
            field=models.ManyToManyField(blank=True, to='lepcismagna.language'),
        ),
    ]
