# Generated by Django 5.0 on 2023-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0006_language_inscription_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=50)),
                ('inscriptions', models.ManyToManyField(blank=True, to='lepcismagna.inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='materials',
            field=models.ManyToManyField(blank=True, to='lepcismagna.material'),
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('inscriptions', models.ManyToManyField(blank=True, to='lepcismagna.inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='object_types',
            field=models.ManyToManyField(blank=True, to='lepcismagna.objecttype'),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(blank=True, max_length=100)),
                ('inscriptions', models.ManyToManyField(blank=True, to='lepcismagna.inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='repositories',
            field=models.ManyToManyField(blank=True, to='lepcismagna.repository'),
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(blank=True, max_length=50)),
                ('inscriptions', models.ManyToManyField(blank=True, to='lepcismagna.inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='techniques',
            field=models.ManyToManyField(blank=True, to='lepcismagna.technique'),
        ),
    ]
