# Generated by Django 5.0 on 2023-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0007_material_inscription_materials_objecttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='emperorimperialfamily',
            name='life',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='emperorimperialfamily',
            name='reign',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
