# Generated by Django 5.0 on 2023-12-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0008_alter_repository_options_emperorimperialfamily_life_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emperorimperialfamily',
            options={'verbose_name_plural': 'emperors and imperial family members'},
        ),
        migrations.AddField(
            model_name='emperorimperialfamily',
            name='regnal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emperorimperialfamily',
            name='life',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='emperorimperialfamily',
            name='reign',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
