# Generated by Django 5.0 on 2023-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0011_userdossier_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abbreviation',
            old_name='inscription_references',
            new_name='inscriptions',
        ),
        migrations.AddField(
            model_name='inscription',
            name='epigraphic_references',
            field=models.ManyToManyField(blank=True, related_name='epigraphic_references', to='lepcismagna.epigraphicreference'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='abbreviations',
            field=models.ManyToManyField(blank=True, related_name='abbreviations', to='lepcismagna.abbreviation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='age_at_death',
            field=models.ManyToManyField(blank=True, related_name='age_at_death', to='lepcismagna.ageatdeath'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='associated_inscr',
            field=models.ManyToManyField(blank=True, related_name='associated_inscr', to='lepcismagna.inscription'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='bibliography_entries',
            field=models.ManyToManyField(blank=True, related_name='bibliography_entries', to='lepcismagna.bibliography'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='lepcismagna.category'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='divine_sacred_beings',
            field=models.ManyToManyField(blank=True, related_name='divine_sacred_beings', to='lepcismagna.divinesacredbeing'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='emperors_imperial_family',
            field=models.ManyToManyField(blank=True, related_name='emperors_imperial_family', to='lepcismagna.emperorimperialfamily'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='erasures',
            field=models.ManyToManyField(blank=True, related_name='erasures', to='lepcismagna.erasure'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='findspots',
            field=models.ManyToManyField(blank=True, related_name='findspots', to='lepcismagna.findspot'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='fragments', to='lepcismagna.fragment'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='lepcismagna.image'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='lepcismagna.language'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='materials', to='lepcismagna.material'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='object_types',
            field=models.ManyToManyField(blank=True, related_name='object_types', to='lepcismagna.objecttype'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='lepcismagna.organization'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to='lepcismagna.person'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personal_names',
            field=models.ManyToManyField(blank=True, related_name='personal_names', to='lepcismagna.personalname'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='place_names',
            field=models.ManyToManyField(blank=True, related_name='place_names', to='lepcismagna.placename'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='repositories', to='lepcismagna.repository'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='symbols',
            field=models.ManyToManyField(blank=True, related_name='symbols', to='lepcismagna.symbol'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='lepcismagna.technique'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='words', to='lepcismagna.word'),
        ),
    ]
