# Generated by Django 5.0 on 2023-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0012_rename_inscription_references_abbreviation_inscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='associated_inscr',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
    ]
