# Generated by Django 5.0 on 2023-12-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0013_alter_inscription_associated_inscr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abbreviation',
            name='inscriptions',
        ),
        migrations.RemoveField(
            model_name='inscriptionbibliography',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='inscriptionbibliography',
            name='inscriptions',
        ),
        migrations.RemoveField(
            model_name='inscriptionreference',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='inscriptionreference',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='epigraphicreference',
            name='inscriptions',
        ),
        migrations.AlterModelOptions(
            name='bibliography',
            options={'verbose_name_plural': 'bibliography entries'},
        ),
        migrations.AddField(
            model_name='abbreviation',
            name='inscription_list',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='epigraphicreference',
            name='inscription_list',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.DeleteModel(
            name='InscriptionAbbreviation',
        ),
        migrations.DeleteModel(
            name='InscriptionBibliography',
        ),
        migrations.DeleteModel(
            name='InscriptionReference',
        ),
    ]
