# Generated by Django 5.0 on 2023-12-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0015_rename_inscription_list_abbreviation_inscriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='associated_inscr',
            new_name='associated_inscriptions',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='findspot_desc',
            new_name='findspot_description',
        ),
    ]
